window._glo = {
	exportHtmlFooter: function () {
		return ''
			+ '<footer style="position:fixed; font-size:.8em; text-align:right; bottom:0px; margin-left:-25px; height:20px; width:100%;">'
			+ 'generated by <a href="http://pad.haroopress.com" target="_blank">haroopad</a>'
			+ '</footer>'
	}
};